// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250303132236_Workspace")]
    partial class Workspace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.CustomFields", b =>
                {
                    b.Property<Guid>("CustomFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CustomersCustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("DropdownOptions")
                        .HasColumnType("longtext");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CustomFieldId");

                    b.HasIndex("CustomersCustomerId");

                    b.ToTable("CustomFields");
                });

            modelBuilder.Entity("backend.Models.CustomFiledValue", b =>
                {
                    b.Property<Guid>("CustomFieldValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomFieldId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CustomFieldsCustomFieldId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("CustomFieldValueId");

                    b.HasIndex("CustomFieldsCustomFieldId");

                    b.ToTable("CustomFiledValues");
                });

            modelBuilder.Entity("backend.Models.Customers", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<bool>("Archived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BillingCity")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingCountry")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingPostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingProvince")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingStreet")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("FaxPhone")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("HomePhone")
                        .HasColumnType("longtext");

                    b.Property<bool>("InvoiceFollowUps")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCompany")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("JobFollowUps")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("MainPhone")
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("MobilePhone")
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("OtherPhone")
                        .HasColumnType("longtext");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<bool>("QuoteFollowUps")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<bool>("TextMessagesEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("VisitReminders")
                        .HasColumnType("tinyint(1)");

                    b.PrimitiveCollection<string>("WorkPhone")
                        .HasColumnType("longtext");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("GoogleId")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("backend.Models.CustomFields", b =>
                {
                    b.HasOne("backend.Models.Customers", null)
                        .WithMany("CustomFields")
                        .HasForeignKey("CustomersCustomerId");
                });

            modelBuilder.Entity("backend.Models.CustomFiledValue", b =>
                {
                    b.HasOne("backend.Models.CustomFields", null)
                        .WithMany("CustomFiledValue")
                        .HasForeignKey("CustomFieldsCustomFieldId");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.HasOne("backend.Models.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("backend.Models.CustomFields", b =>
                {
                    b.Navigation("CustomFiledValue");
                });

            modelBuilder.Entity("backend.Models.Customers", b =>
                {
                    b.Navigation("CustomFields");
                });
#pragma warning restore 612, 618
        }
    }
}
