// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250508222210_ServiceItem")]
    partial class ServiceItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.CustomFields", b =>
                {
                    b.Property<Guid>("CustomFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CustomersCustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("DropdownOptions")
                        .HasColumnType("longtext");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CustomFieldId");

                    b.HasIndex("CustomersCustomerId");

                    b.ToTable("CustomFields");
                });

            modelBuilder.Entity("backend.Models.CustomFiledValue", b =>
                {
                    b.Property<Guid>("CustomFieldValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomFieldId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CustomFieldsCustomFieldId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("CustomFieldValueId");

                    b.HasIndex("CustomFieldsCustomFieldId");

                    b.ToTable("CustomFiledValues");
                });

            modelBuilder.Entity("backend.Models.CustomerPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CustomersCustomerId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsReceiveMessage")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneType")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomersCustomerId");

                    b.ToTable("CustomerPhones");
                });

            modelBuilder.Entity("backend.Models.Customers", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Archived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("InvoiceFollowUps")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCompany")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("JobFollowUps")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("QuoteFollowUps")
                        .HasColumnType("tinyint(1)");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<bool>("VisitReminders")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("backend.Models.Notes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CustomersCustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NoteText")
                        .HasColumnType("longtext");

                    b.Property<string>("PathFile")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomersCustomerId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("backend.Models.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CustomersCustomerId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsBillingAddress")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomersCustomerId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("GoogleId")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("backend.Models.CustomFields", b =>
                {
                    b.HasOne("backend.Models.Customers", null)
                        .WithMany("CustomFields")
                        .HasForeignKey("CustomersCustomerId");
                });

            modelBuilder.Entity("backend.Models.CustomFiledValue", b =>
                {
                    b.HasOne("backend.Models.CustomFields", null)
                        .WithMany("CustomFiledValue")
                        .HasForeignKey("CustomFieldsCustomFieldId");
                });

            modelBuilder.Entity("backend.Models.CustomerPhone", b =>
                {
                    b.HasOne("backend.Models.Customers", null)
                        .WithMany("CustomerPhones")
                        .HasForeignKey("CustomersCustomerId");
                });

            modelBuilder.Entity("backend.Models.Notes", b =>
                {
                    b.HasOne("backend.Models.Customers", null)
                        .WithMany("Notes")
                        .HasForeignKey("CustomersCustomerId");
                });

            modelBuilder.Entity("backend.Models.Property", b =>
                {
                    b.HasOne("backend.Models.Customers", null)
                        .WithMany("Properties")
                        .HasForeignKey("CustomersCustomerId");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.HasOne("backend.Models.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("backend.Models.CustomFields", b =>
                {
                    b.Navigation("CustomFiledValue");
                });

            modelBuilder.Entity("backend.Models.Customers", b =>
                {
                    b.Navigation("CustomFields");

                    b.Navigation("CustomerPhones");

                    b.Navigation("Notes");

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
