import { TCustomer } from './Customer';
import { TAddLineItem, TLineItem } from './LineItem';
import { TNote } from './Note';
import { TProperty } from './Property';
import { TStatusHistory } from './StatusHistory';

export type TJob = {
  jobId: string;
  title: string;
  description: string;
  customerId: string;
  customer: TCustomer;
  propertyId: string;
  property: TProperty;
  jobType: string;
  repeats: string;
  lineItems: TLineItem[];
  status: string;
  statusHistory: TStatusHistory[];
  priority: string;
  startDate: string;
  startTime: string;
  arrivalWindowStart: string;
  arrivalWindowEnd: string;
  duration: number;
  estimatedDurationMinutes: number;
  timeZone: string;
  assignedTeamMemberIds: string[];
  teamNotes: TNote[];
  paymentStatus: string;
  depositAmount: number;
  subtotal: number;
  taxAmount: number;
  discountAmount: number;
  totalAmount: number;
  sendInvoice: boolean;
  sendReminder: boolean;
  reminderDaysBefore: number;
  confirmationSent: boolean;
  reminderSent: boolean;
  invoiceSent: boolean;
  createdAt: string;
  updatedAt: string;
  completedAt: string;
  createdBy: string;
  source: string;
  tags: string[];
  customerNotes: string;
  internalNotes: string;
};

export type TAddJob = {
  title: string;
  description?: string;
  customerId: string;
  propertyId?: string;
  jobType: string;
  repeats: string;
  lineItems: TAddLineItem[];
  status: string;
  priority: string;
  startDate: string;
  startTime: string;
  arrivalWindowStart: string;
  arrivalWindowEnd: string;
  duration: number;
  estimatedDurationMinutes: number;
  timeZone: string;
  assignedTeamMemberIds?: string[];
  paymentStatus: string;
  sendInvoice: boolean;
  sendReminder: boolean;
  reminderDaysBefore: number;
  createdBy?: string;
};
