export const serviceCategories = [
  'Plumbing Services',
  'HVAC Services',
  'Electrical Services',
  'Landscaping & Gardening',
  'Cleaning Services',
  'Home Renovation',
  'Appliance Repair',
  'Pest Control',
  'Roofing & Gutters',
  'Carpentry & Woodwork',
  'Painting Services',
  'Flooring Installation',
  'Security Systems',
  'Pool Maintenance',
  'Solar Panel Installation',
  'Window Installation & Repair',
  'Masonry & Concrete',
  'Locksmith Services',
  'Moving Services',
  'General Contractor',
  'Other',
];
