export const sidebarItems = [
  {
    name: 'Home',
    icon: 'https://api.iconify.design/lucide:home.svg',
    slug: 'home',
    section: 'general',
  },
  {
    name: 'Calendar',
    icon: 'https://api.iconify.design/lucide:calendar.svg',
    slug: 'calendar',
    section: 'general',
  },
  {
    name: 'Customers',
    icon: 'https://api.iconify.design/lucide:users.svg',
    slug: 'customers',
    section: 'general',
  },
  {
    name: 'Leads',
    icon: 'https://api.iconify.design/lucide:user-plus.svg',
    slug: 'leads',
    section: 'general',
  },
  {
    name: 'Quotes',
    icon: 'https://api.iconify.design/lucide:file-text.svg',
    slug: 'quotes',
    section: 'general',
  },
  {
    name: 'Jobs',
    icon: 'https://api.iconify.design/lucide:briefcase.svg',
    slug: 'jobs',
    section: 'general',
  },
  {
    name: 'Invoices',
    icon: 'https://api.iconify.design/lucide:receipt.svg',
    slug: 'invoices',
    section: 'general',
  },
  {
    name: 'Employees',
    icon: 'https://api.iconify.design/lucide:user-check.svg',
    slug: 'employees',
    section: 'business',
  },
  {
    name: 'Pricebook',
    icon: 'https://api.iconify.design/lucide:book.svg',
    slug: 'pricebook',
    section: 'business',
  },
  {
    name: 'Reports',
    icon: 'https://api.iconify.design/lucide:bar-chart-3.svg',
    slug: 'reports',
    section: 'business',
  },
  {
    name: 'Marketing',
    icon: 'https://api.iconify.design/lucide:megaphone.svg',
    slug: 'marketing',
    section: 'business',
  },
  {
    name: 'Settings',
    icon: 'https://api.iconify.design/lucide:settings.svg',
    slug: 'settings',
    section: 'system',
  },
  {
    name: 'Help & Support',
    icon: 'https://api.iconify.design/lucide:help-circle.svg',
    slug: 'help-support',
    section: 'system',
  },
];
