import {
  BarChart3,
  BookOpen,
  BriefcaseBusiness,
  CalendarDays,
  ClipboardList,
  FileText,
  Home,
  Receipt,
  Settings,
  UserCheck,
  UserPlus,
  Users,
} from 'lucide-react';

export const sidebarItems = [
  {
    name: 'Home',
    Icon: Home,
    slug: 'home',
    section: 'general',
  },
  {
    name: 'Calendar',
    Icon: CalendarDays,
    slug: 'calendar',
    section: 'general',
  },
  { name: 'Dispatch', Icon: ClipboardList, slug: 'dispatch', section: 'general' },
  { name: 'My day', Icon: CalendarDays, slug: 'my-day', section: 'general' },
  {
    name: 'Customers',
    Icon: Users,
    slug: 'customers',
    section: 'general',
  },
  {
    name: 'Leads',
    Icon: UserPlus,
    slug: 'leads',
    section: 'general',
  },
  {
    name: 'Quotes',
    Icon: FileText,
    slug: 'quotes',
    section: 'general',
  },
  {
    name: 'Jobs',
    Icon: BriefcaseBusiness,
    slug: 'jobs',
    section: 'general',
  },
  {
    name: 'Invoices',
    Icon: Receipt,
    slug: 'invoices',
    section: 'general',
  },
  {
    name: 'Employees',
    Icon: UserCheck,
    slug: 'employees',
    section: 'business',
  },
  {
    name: 'Pricebook',
    Icon: BookOpen,
    slug: 'pricebook',
    section: 'business',
  },
  {
    name: 'Reports',
    Icon: BarChart3,
    slug: 'reports',
    section: 'business',
  },
  {
    name: 'Settings',
    Icon: Settings,
    slug: 'settings',
    section: 'system',
  },
];
