import { FormEvent, useState } from 'react';
import { CalendarDays, CheckCircle2, Loader2 } from 'lucide-react';
import { useParams } from 'react-router';
import { createBooking } from '../services/Public';

export default function Booking() {
  const { workspaceId = '' } = useParams();
  const [sent, setSent] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setLoading(true); setError(''); const form = new FormData(event.currentTarget); try { await createBooking(workspaceId, { firstName: form.get('firstName'), lastName: form.get('lastName'), email: form.get('email'), phoneNumber: form.get('phoneNumber'), description: form.get('description'), preferredStartDateTime: form.get('preferredStartDateTime') || null }); setSent(true); } catch { setError('We could not send your request. Please try again.'); } finally { setLoading(false); } };
  if (sent) return <main className='min-h-screen grid place-items-center bg-gray-50 p-6'><div className='max-w-md text-center'><CheckCircle2 className='mx-auto h-12 w-12 text-bg-primary' /><h1 className='mt-4 text-2xl font-semibold'>Request received</h1><p className='mt-2 text-gray-600'>The business will be in touch to confirm a time.</p></div></main>;
  return <main className='min-h-screen bg-gray-50 px-4 py-10 sm:px-6'><div className='mx-auto max-w-lg'><div className='mb-7'><CalendarDays className='h-8 w-8 text-bg-primary' /><h1 className='mt-3 text-2xl font-semibold text-gray-900'>Request service</h1><p className='mt-1 text-gray-600'>Tell us what you need and we will follow up with availability.</p></div><form onSubmit={submit} className='space-y-4 border border-gray-200 bg-white p-5 shadow-sm sm:p-7'><div className='grid gap-4 sm:grid-cols-2'><label className='text-sm font-medium'>First name<input required name='firstName' className='mt-1 w-full border border-gray-300 p-2.5' /></label><label className='text-sm font-medium'>Last name<input required name='lastName' className='mt-1 w-full border border-gray-300 p-2.5' /></label></div><label className='block text-sm font-medium'>Email<input type='email' name='email' className='mt-1 w-full border border-gray-300 p-2.5' /></label><label className='block text-sm font-medium'>Phone<input name='phoneNumber' className='mt-1 w-full border border-gray-300 p-2.5' /></label><label className='block text-sm font-medium'>Preferred date and time<input type='datetime-local' name='preferredStartDateTime' className='mt-1 w-full border border-gray-300 p-2.5' /></label><label className='block text-sm font-medium'>What can we help with?<textarea required name='description' rows={4} className='mt-1 w-full border border-gray-300 p-2.5' /></label>{error && <p className='text-sm text-red-600' role='alert'>{error}</p>}<button disabled={loading} className='flex w-full items-center justify-center gap-2 bg-bg-primary px-4 py-3 font-medium text-white disabled:opacity-60'>{loading && <Loader2 className='h-4 w-4 animate-spin' />}Send request</button></form></div></main>;
}
