import { useEffect, useState } from 'react';
import { UserRound } from 'lucide-react';
import Sidebar from '../components/Sidebar/Sidebar';
import Navbar from '../components/Navbar/Navbar';
import { GetJobsByWorkspaceId, UpdateJob } from '../services/Job';
import { GetEmployeesByWorkspace } from '../services/Employee';
import { useAuth } from '../context/AuthProvider';
import { TJob } from '../types/Job';
import { TEmployee } from '../types/Employee';

export default function DispatchBoard() {
  const { user } = useAuth(); const [jobs, setJobs] = useState<TJob[]>([]); const [employees, setEmployees] = useState<TEmployee[]>([]); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [error, setError] = useState('');
  const load = async () => { if (!user?.workspace) return; const [jobResponse, employeeResponse] = await Promise.all([GetJobsByWorkspaceId(user.workspace.id, 1, 200), GetEmployeesByWorkspace(user.workspace.id)]); setJobs(jobResponse.data.payload?.items ?? []); setEmployees(employeeResponse.data.payload ?? []); };
  useEffect(() => { load().catch(() => setError('Could not load the dispatch board.')); }, [user?.workspace]);
  const visibleJobs = jobs.filter((job) => new Date(job.startDateTime).toISOString().slice(0, 10) === date);
  const assign = async (job: TJob, employee: TEmployee) => { try { await UpdateJob({ id: job.id, title: job.title, startDateTime: job.startDateTime, endDateTime: job.endDateTime, assignedTeamMembers: [employee] }); await load(); } catch { setError('That assignment conflicts with another job or is outside working hours.'); } };
  return <div className='flex min-h-screen bg-gray-50'><Sidebar /><div className='flex-1 md:ml-64'><Navbar /><main className='p-4 sm:p-6'><div className='mb-6 flex flex-wrap items-end justify-between gap-4'><div><h1 className='text-2xl font-semibold'>Dispatch board</h1><p className='text-sm text-gray-500'>Drag a job onto a technician to assign it.</p></div><label className='text-sm font-medium'>Day<input type='date' value={date} onChange={(event) => setDate(event.target.value)} className='ml-2 border border-gray-300 bg-white p-2' /></label></div>{error && <p role='alert' className='mb-4 text-sm text-red-600'>{error}</p>}<div className='grid gap-4 xl:grid-cols-2'>{employees.map((employee) => <section key={employee.id} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { const id = event.dataTransfer.getData('job-id'); const job = visibleJobs.find((item) => item.id === id); if (job) void assign(job, employee); }} className='min-h-48 border border-gray-200 bg-white p-4'><div className='flex items-center gap-2 border-b border-gray-100 pb-3'><UserRound className='h-5 w-5 text-bg-primary' /><div><h2 className='font-medium'>{employee.user?.fullName}</h2><p className='text-xs text-gray-500'>{employee.skills?.join(', ') || 'General technician'}</p></div></div><div className='mt-3 space-y-2'>{visibleJobs.filter((job) => job.assignedTeamMembers?.some((member) => member.id === employee.id)).map((job) => <div key={job.id} draggable onDragStart={(event) => event.dataTransfer.setData('job-id', job.id)} className='cursor-grab border-l-4 border-bg-primary bg-green-50 p-3 text-sm'><p className='font-medium'>{job.title}</p><p className='text-gray-600'>{new Date(job.startDateTime).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })} - {new Date(job.endDateTime).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</p></div>)}</div></section>)}<section onDragOver={(event) => event.preventDefault()} className='border border-dashed border-gray-300 bg-white p-4 xl:col-span-2'><h2 className='font-medium'>Unassigned</h2><div className='mt-3 flex flex-wrap gap-2'>{visibleJobs.filter((job) => !job.assignedTeamMembers?.length).map((job) => <div key={job.id} draggable onDragStart={(event) => event.dataTransfer.setData('job-id', job.id)} className='cursor-grab border border-gray-200 bg-gray-50 p-3 text-sm'><p className='font-medium'>{job.title}</p><p className='text-gray-600'>{job.customer?.fullName}</p></div>)}</div></section></div></main></div></div>;
}
